name: example
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.2.0
  path: ^1.9.1
  spring_dart:
    git:
      url: https://github.com/tiagualvs/spring_dart.git
      path: spring_dart
      ref: dev
  spring_dart_sql:
    git:
      url: https://github.com/tiagualvs/spring_dart.git
      path: spring_dart_sql
      ref: dev
  sqlite3: ^2.9.0
  tempoid: ^0.4.0

dev_dependencies:
  build_runner: ^2.6.1
  spring_dart_gen:
    git:
      url: https://github.com/tiagualvs/spring_dart.git
      path: spring_dart_gen
      ref: dev
  lints: ^6.0.0
  test: ^1.24.0
