name: example
description: A sample command-line application.
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.2.0
  path: ^1.9.1
  spring_dart:
  spring_dart_sql:
  sqlite3: ^2.9.0
  tempoid: ^0.4.0

dev_dependencies:
  build_runner: ^2.6.1
  spring_dart_gen:
  lints: ^6.0.0
  test: ^1.24.0
