name: spring_dart_core
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  dson_adapter: ^1.2.0+2
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0