name: spring_dart_core
description: A starting point for Dart libraries or applications.
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_multipart: ^2.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0