name: spring_dart_gen
description: A starting point for Dart libraries or applications.
version: 0.0.1

publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  spring_dart_core:
  spring_dart_sql:
  build: ^3.0.1
  source_gen: ^3.1.0
  analyzer: ^8.1.1
  dart_style: ^3.1.2
  glob: ^2.1.3
  path: ^1.9.1
  strings: ^4.0.1
  yaml: ^3.1.3
  sqlite3: ^2.9.0
  inflection3: ^0.5.3+2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
