name: spring_dart_sql
description: A starting point for Dart libraries or applications.
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
